spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: cooperative
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ryzhevichs@gmail.com
    password: Stepan2016
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false